name: Build and Release Mod

on:
  workflow_dispatch:
  push:
    branches:            # <--- 这里从 tags 改为 branches
      - "1.21.6-fix"     # <--- 这里写你的分支名

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant Execute Permission
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create Release
        uses: softprops/action-gh-release@v2
        # if: startsWith(github.ref, 'refs/tags/')  <--- 删掉或注释掉这一行，因为现在我们是分支触发
        with:
          files: build/libs/*.jar
          name: "Auto Build 1.21.6-fix"   # 发布标题
          tag_name: "build-${{ github.run_number }}" # 必须指定一个 tag 名字，这里用构建序号自动命名
          make_latest: true
